version: 2
jobs:
  build:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run:
          command: |
            apt-get update -q
            apt-get install -y --no-install-recommends git python3 python3-requests
            ./.circleci/debops-ci ci
