version: 2
# DEB_GPG_KEY is set to
# gpg -a --export-secret-keys B5A08F01796E7F521861B449372D1FF271F2DD50 | base64 --wrap=0
# because CircleCI cannot handle multiline env vars
jobs:
  create_deb_package:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run: echo "deb http://deb.debian.org/debian buster-backports main" > /etc/apt/sources.list.d/backports.list
      - run: apt-get update -q
      - run: apt-get install -q -y --no-install-recommends git python3 python3-requests s3cmd python3-gnupg wget
      - run: wget https://raw.githubusercontent.com/ooni/sysadmin/master/tools/debops-ci
      - run: chmod +x debops-ci
      - run: |
          export DEB_GPG_KEY=$(echo $DEB_GPG_KEY | base64 -d)
          ./debops-ci --show-commands ci --bucket-name ooni-internal-deb

workflows:
  version: 2

  my_workflows:
    jobs:
      - create_deb_package:
          context: ooni
